### ISSUE TITLE
Unsubscribe

### ISSUE THREAD

**Issue by aboeglin** [staltz/callbag-basics#14]
Hi André !

I just found out about your spec. I find it very nice and I love the idea of a new angle on that topic. I have been playing around with it last night and built my own operators ( a partition mostly ). When I get the time I'll do a rewrite with tests and may well publish it.

Back on the topic. I have read your article about repos without maintainers. There as well I really like your philosophy and I tend to read more and more open source code. I have to say I've been reading the rxjs implementation of partition before I gave it a go. So, I don't want to bother you too much, but maybe you could give me a direction. I'd like to implement an unsubscribe operator. I know I should use the type 2 for that, but I'm not sure how to tackle it.

**Comment by staltz** [comment]
Hi @aboeglin ! Take a look at https://github.com/zebulonj/callbag-subscribe it seems to be what you were looking for :)
