### ISSUE TITLE
How does one compose/combine operators without a source/sink?

### ISSUE THREAD

**Issue by aaronshaf** [staltz/callbag-basics#15]

**Comment by aaronshaf** [comment]
Perhaps use lodash's `flow`?

**Comment by staltz** [comment]
Check the docs for pipe :)

**Comment by aaronshaf** [comment]
```
function pipe(...cbs) {
  let res = cbs[0];
  for (let i = 1, n = cbs.length; i < n; i++) res = cbs[i](res);
  return res;
}
```

`pipe` seems to assume that the first argument is always a source. I want to basically construct an operator pipeline, and then later use it with a source and a sink.

**Comment by aaronshaf** [comment]
Thanks! I figured it out.
