### ISSUE TITLE
fromObject

### ISSUE THREAD

**Issue by aboeglin** [staltz/callbag-basics#16]
Hi,

In RxJS we can write something like this : Observable.of({}).subscribe(...). I need to build a similar operator for callbags but I can't seem to get it to work.

I have tried a naive implementation which is :

```javascript
export const fromObject = obj => (start, sink) => {
	if (start !== 0) return;

	sink(0, (t) => {});
	sink(1, obj);
	sink(2);
};
```

So the idea is, I greet the sink, I send him the object, and I terminate it. The problem arises with merge() which gives me a "talkback is not a function". After looking at the code of merge, it seems that the issue comes from that line : ```if (++startCount === n) sink(0, talkback);```. When it's looped on, the talkbacks are not set yet at the time I send my sink(1, obj). I'm not saying there's something wrong with the merge operator, but I look for guidance on how to tackle the problem and build my source.

The goal is to have a synchronous source that emits once and completes. And that plays nicely with the current ecosystem.

**Comment by staltz** [comment]
Hi @aboeglin , isn't this a issue on callbag-merge? (I'm brief because on mobile)

**Comment by aboeglin** [comment]
It's definitely possible yes. I think it's the way it handles things. I'll investigate further later. I need to do a break to work on other things right now but I'll come back to it.

If you have any idea it's welcome though. If I find a fix I'll propose a PR for callbag-merge. But in the idea you validate my implementation of the source ?

**Comment by staltz** [comment]
Maybe `fromObject` should be made a pullable, not a listenable. And then, `merge` is only for listenables.

**Comment by glowforge-opensource** [comment]
`fromObject` could also be include a simple async delay. It would be equivalent to the following:
```javascript
export const fromObject = obj => pipe(interval(0), map(() => obj), take(1));
```
This would likely play nicely with `merge`, if `fromObj` was to act as a listenable.

**Comment by aboeglin** [comment]
Yes I thought of that and made a working implementation. But in my case I'd need to be able to merge it.

**Comment by staltz** [comment]
I think you want to sample or sampleCombine it. Merge is only for listenables. Outside that, it has undefined behavior

**Comment by aboeglin** [comment]
That's why I'd like it to be a listenable.

**Comment by staltz** [comment]
It's a value (the object) which can be pulled. By making it listenable, the pull happens upon `0`. By making it pullable, the pull happens upon `1`. In the end of the day it's about pulling one value out of the callbag source.

**Comment by aboeglin** [comment]
Yes I understand the difference I think. The code I put above is the listenable. And I'd like it to be pushed when subscribed on.

**Comment by staltz** [comment]
Okay I think I found a problem with merge, I wrote a new implementation and will now write tests. Keep an eye to see the next version of merge. Thanks for reporting.

**Comment by aboeglin** [comment]
Thanks ! I would have been happy to do it though, but I look forward to have a look at it !
