### ISSUE TITLE
Core Callbag Basics Feature: callbag-emitter

### ISSUE THREAD

**Issue by simplygreatwork** [staltz/callbag-basics#18]
`callbag-basics` ought to have a very simple technique to introduce/push values onto a stream. The ability to emit any value onto the stream manually is more important than fromEvent, fromPromise, fromIterator, and fromObservable. Consider that all of these "from" modules do not belong in `callbag-basics`. Consider that `callbag-basics` ought to have a single basic module for introducing values onto a stream.

**Comment by staltz** [comment]
Hi @simplygreatwork !

> The ability to emit any value onto the stream manually **is more important** than fromEvent, fromPromise, fromIterator, and fromObservable.

I disagree, I think the opposite is more important. But it doesn't matter, we don't need to agree! Just npm install https://github.com/staltz/callbag-subject and now you have the emitter that you wanted :)

**Comment by simplygreatwork** [comment]
André, thank you for pointing me to `callbag-subject`. I always scour for libraries. Recently I've been scouring for a good stream library. I've evaluated highland, kefir, flyd, lazy. I stumbled upon xstream, then rx-toy, and finally callbag. Brilliant work, sir.
