### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by andywer** [staltz/callbag-basics#2]
Hey @staltz.

I like the stuff you build, but I am wondering what will happen if there is an error in one of the source factories. Observables or similar libraries like `xstream` always have a value handler and an error handler for that reason.

Maybe you can elaborate that a bit in the README.

Cheers

**Comment by staltz** [comment]
Are you talking about callbag or callbag-basics? In this library (basics), there is no error propagation, but you could build operators (like RxJS, but for callbags) that catch errors, and common operators like map could have a try/catch internally. My own callbag-map doesn't have an internal try/catch, but it could have. The reason I didn't do that for map is that I think error propagation isn't really useful for those cases (if there is a syntax error in `f` from `map(f)`, no amount of retry subscriptions will fix it). Errors make a lot of sense for AJAX though.

Callbag as a spec supports error handling. It's the case where the sink is called with `sink(2, err)` as arguments. Successful completion is just `sink(2)`.

**Comment by staltz** [comment]
E.g. read here about Termination: https://github.com/callbag/callbag#protocol
