### ISSUE TITLE
Pin callbag* deps to their major versions?

### ISSUE THREAD

**Issue by ds82** [staltz/callbag-basics#26]
From what I observed you follow semantic versioning in all your `callbag-*` packages. Since patch and minor releases therefore should not contain any breaking changes, can we pin all deps in callbag-basics to their major versions?

```
    "callbag": "1.0.x",
    "callbag-for-each": "1.0.x",
    "callbag-from-obs": "1.1.x",
    ...
```

==>

```
    "callbag": "1",
    "callbag-for-each": "1",
    "callbag-from-obs": "1",
    ...
```

I can make a PR for this if you agree.

**Comment by staltz** [comment]
Yes, agreed!

**Comment by staltz** [comment]
Yes, agreed!
