### ISSUE TITLE
Is forEach violating the callbag spec?

### ISSUE THREAD

**Issue by dmitriz** [staltz/callbag-basics#31]
From [Callbag Spec](https://github.com/callbag/callbag#summary):

> Every consumer of data is a function (type: number, payload?: any) => void

However, [the `forEach` factory](https://github.com/staltz/callbag-for-each/blob/master/readme.js) returns a function of different signature:
```js
const forEach = operation => source => {...}
```

So strictly speaking, it is not a callbag factory?

**Comment by franciscotln** [comment]
the actual `forEach` is what is passed to the source as:
```js
(t, d) => {
    if (t === 0) talkback = d;
    if (t === 1) operation(d);
    if (t === 1 || t === 0) talkback(1);
  }
```
That's the consumer. What may have confused you is the fact that this factory is curried
```js
const forEach = (operation, source) => {
  let talkback;
  source(0, function forEachSink(t, d) {
    if (t === 0) talkback = d;
    if (t === 1) operation(d);
    if (t === 1 || t === 0) talkback(1);
  });
};
```
Nothing is actually being returned here, it's just for pipe/composition sake.

**Comment by dmitriz** [comment]
Hm... that function is only inside the code, but it is not what is returned by the factory.
If `forEach` is made uncurried, it would return `undefined` - not a callbag again.

There must be something wrong with my understanding of the spec then.
I was expecting a callbag sink factory to return a callbag `sink` as described here: 
https://github.com/callbag/callbag/blob/master/getting-started.md#creating-a-sink

> A listener sink is a callbag function:
```js
function sink(type, data) {
}
```

So I was expecting `forEach` to return a sink of that signature.
And then to initiate a handshake with 
```js
sink(0, source)
``` 
while right now it is a direct call:
```js
sink(source)
```

**Comment by staltz** [comment]
Interesting question. Being precise, yes, the `forEach` factory does not produce a callback sink, so it's not a factory of a callbag. But also so aren't operators. Most operators take this shape:

```
params => inSource => outSource
```

For instance map:

```js
const map = f => inSource => function outSource(start, sink) {
  if (start !== 0) return;
  source(0, (t, d) => {
    sink(t, t === 1 ? f(d) : d)
  });
};
```

And forEach has a similar shape:

```
params => inSource => void
```

So technically correctly, `forEach` is a factory of a consumer of sources, and internally it creates a sink. If `forEach` were a factory of sinks, it would be cumbersome to use in `pipe`:

```js
pipe(
  fromEvent(document, 'click'),
  filter(ev => ev.target.tagName === 'BUTTON'),
  map(ev => ({x: ev.clientX, y: ev.clientY})),
  source => forEach(coords => console.log(coords))(0, source)
);
```

If we would do that, it would also make sense for the library to export a consumer of sources, e.g.:

```js
const applyForEach = require('callbag-for-each/apply')

pipe(
  fromEvent(document, 'click'),
  filter(ev => ev.target.tagName === 'BUTTON'),
  map(ev => ({x: ev.clientX, y: ev.clientY})),
  applyForEach(coords => console.log(coords))
);
```

And it would turn out that `callbag-for-each/apply` would be used in practice, while `callbag-for-each` almost never, so it just makes sense to export the consumer of the source instead of the factory of sink.

**Comment by dmitriz** [comment]
@staltz Thank you for the clarification!
I was really attracted to the callbag spec by its uniformity of the interface for both source and sink.

Also, once sink also sends data back to source, the source-sink distinction seems to disappear, so the interface uniformity make total sense. Similarly, the bi-directional handshake looks symmetric: 
```js
// all equivalent?
source(0, sink)     
sink(0, source)  
init(0, source, sink)
``` 
could be, in principle, equivalent legal ways to couple any two callbags to initiate their bidirectional communication. The nature of what exactly happens in that coupling is, of course, dependent on the specific implementation of the participants, but the coupling interface remains uniform, where arbitrary dependency graphs can be created by uniformly coupling or decoupling any pair of callbags.

> Being precise, yes, the `forEach` factory does not produce a callback sink, so it's not a factory of a callbag. But also so aren't operators.

I am a bit lost here: isn't `map` (and other unary operators) sending callbag to callbag?
```js
const map = f => source => 
    (start, sink) => {...}  // callbag
```
or `scan`
```js
const scan = (reducer, seed) => source => 
    (start, sink) => {...}  // callbag
```
or `merge`
```
const merge = (...sources) =>
    (start, sink) => {...}  // callbag
```

Also, maybe in reverse to `merge`, a `split` operator into two (or several) callbags can be useful:
```js
const split => pred => callbag => [
    callbag1  // data  with pred(data) === true
    callbag2  // otherwise
]
```


> So technically correctly, forEach is a factory of a consumer of sources, and internally it creates a sink.

Is a *consumer* here any function of the signature `consumer = callbag => void`? Which is, therefore, itself not a callbag? 

Alternatively, we could keep the uniform interface, while creating consumer out of any callbag  via `consumer(sink)` or `consumer(sink)(source)` to consume  the`source`, and then inside the `pipe` function:

```js
pipe(
  fromEvent(document, 'click'),
  filter(ev => ev.target.tagName === 'BUTTON'),
  map(ev => ({x: ev.clientX, y: ev.clientY})),
  consume(forEach)
);
```

That code seems now generic, where `forEach` would be replaceable with *any* callbag 
and the`consume` operator emphasizes the special role of the last argument of the `pipe`.
While currently, that special role of the last argument in pipeline seems hidden in the definition of `forEach` that isn't exchangeable for another callbag `sink` due to the interface non-uniformity.

**Comment by staltz** [comment]
> I am a bit lost here: isn't map (and other unary operators) sending callbag to callbag?

Well, yes, that's what I meant when I said the shape is

```
params => inSource => outSource
```

because both inSource and outSource are callbags.

> Is a consumer here any function of the signature consumer = callbag => void? Which is, therefore, itself not a callbag?

Yes and yes.

> Alternatively, we could keep the uniform interface, while creating consumer out of any callbag via `consume(sink)`

Yes, we could do that. If the uniformity of "they are all literally callbags" is important to you, go ahead and publish `callbag-consume`, I bet it's a tiny effort. I'm inclined to keeping `forEach` as it is now, because breaking changes are *breaking*, and not everyone might prefer the uniformity guarantee if it costs them a breaking change. I stand that there are no "official utils" for the callbag community, so I'm happy that `forEach` is not authoritative over `consume`.
