### ISSUE TITLE
callbag-debounce

### ISSUE THREAD

**Issue by ecwyne** [staltz/callbag-basics#7]
Love the idea! It's simple and elegant.

I wanted to write `debounce` to make sure I understood the philosophy of `callbag`. Before I published it, I was wondering if you could just take a quick look and make sure it's written correctly. My testing seems to work, but this is totally new to me.

```javascript
const debounce = duration => source => (start, sink) => {
  if (start !== 0) return;
  let latest = 0;
  let talkback;
  source(0, (t, d) => {
    if (t === 0) {
      talkback = d;
      sink(t, d);
    } else if (t === 1) {
      const now = Date.now();
      if (now >= latest + duration) {
        latest = now;
        sink(t, d);
      } else {
        talkback(1);
      }
    } else {
      sink(t, d);
    }
  });
};
```

**Comment by staltz** [comment]
Hi @ecwyne ! Cool! Debounce is needed :)

Is this supposed to work for both pullables and listenables? It seems like it's only for pullables, because it calls `talkback(1)` (that's a request upwards, so it's a pull). To support listenables, I think there is no other way than using some setTimeout.

**Comment by ecwyne** [comment]
I very much used `callbag-filter` as a template for this `debounce` implementation. `callbag-filter` says that it works on both pullables and listenables and also calls [`talkback(1)`](https://github.com/staltz/callbag-filter/blob/master/index.js#L10)

This implementation seems to work with listenables.

```javascript
pipe(
  interval(1000),
  debounce(2000),
  observe(console.log)
);
// 0
// 2 (2 seconds later)
// 4 (2 seconds later)
// 6 (2 seconds later)
```

**Comment by shaug** [comment]
An `interval(1000)` passed to a `debounce(2000)` should never emit anything, according to my understanding of how debounce should work.

http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-debounceTime

My understanding of `debounce(2000)` is to emit the last emitted item after 2s of inactivity. But `interval(1000)` is always emitting every 1s, so `debounce(2000)` would keep resetting and thus never emit.

This is an off-the-top-of-my-head, completely untested implementation of how I think debounce should work (RxJS calls this `debounceTime`). Every data event from the source sets a timer to emit that data to the sink. Every event from the source clears any previous timer.

```javascript
const debounceTime = duration => source => (start, sink) => {
  if (start !== 0) return;
  let timeout;
  start(0, (t, d) => {
    // every event clears the existing timeout, if any
    if (timeout) timeout = clearTimeout(timeout);
    if (t === 1) timeout = setTimeout(() => sink(1, d), duration);
    else sink(t, d);
  });
}
```
