### ISSUE TITLE
Utility for building callbags

### ISSUE THREAD

**Issue by ecwyne** [staltz/callbag-basics#8]
As I read through the source code, I see a lot of the following

```javascript
(t, d) => {
  if (t == 0){
    ...
  } else if (t == 1){
    ...
  } else {
    ...
  }
}
```

I've typed up a quick helper to create these callbags and was wondering if you think that it would be useful more widely.

```javascript
const build = cbs => (t, d) => {
  const arr = cbs instanceof Array ? cbs : [ cbs.start, cbs.data, cbs.end ];
  arr[t] && arr[t](d)
}
```

This allows you to create a callbag passing either an object with `{start, data, end}` functions or an array of functions.

```javascript
build({
  start(d){
    ...
  },
  data(d){
    ...
  },
  end(d){
    ...
  }
});

build([
  d => ...,
  d => ...,
  d => ...
])

const interval = period => build({
  start(sink){
    let i = 0;
    const id = setInterval(() => sink(1, i++), period);
    sink(0, build({ end: () => clearInterval(id) }));
  }
})
```

I'd be interested to hear what feedback you have. Thank you for your time and for your novel thoughts on Observables and AsyncIterables!

**Comment by staltz** [comment]
That's a decent idea! As long as it follows the spec, any utility is valid :)
I'd still use the raw version myself, but that's just me. Feel free to publish any utility you think makes sense.
